FROM ubuntu:focal

WORKDIR /app

RUN apt-get update && apt-get -y install curl gnupg lsb-release
RUN curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
RUN echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list && \
apt-get update && apt-get install -y migrate

COPY shared/migrations /migrations
ENTRYPOINT ["migrate"]
