postgresql:
  address: "localhost"
  port: 5432
  user: "user"
  password: "password"
  database: "merge"

rabbit:
  host: "localhost"
  port: 5672
  user: "guest"
  password: "guest"

redis:
  host: "localhost"
  port: 6379
